apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/modeseven/scheduler.git
    app.quarkus.io/build-timestamp: 2020-11-04 - 12:12:41 +0000
    app.quarkus.io/commit-id: cfd678719658f4bd94e4cd59ef89db15e5eabd71
    fluxcd.io/automated: "true"
  labels:
    app.kubernetes.io/name: scheduler-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: scheduler-api
  namespace: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler-api
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/modeseven/scheduler.git
        app.quarkus.io/build-timestamp: 2020-11-04 - 12:12:41 +0000
        app.quarkus.io/commit-id: cfd678719658f4bd94e4cd59ef89db15e5eabd71
      labels:
        app.kubernetes.io/name: scheduler-api
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
      namespace: scheduler
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: scheduler-config
        image: docker.io/modeseven/scheduler-api:dcebe3190482957d87a14d27d69cdc3b3fac2899
        imagePullPolicy: Always
        name: scheduler-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP