apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/modeseven/scheduler.git
    app.quarkus.io/build-timestamp: 2020-11-04 - 12:12:41 +0000
    app.quarkus.io/commit-id: cfd678719658f4bd94e4cd59ef89db15e5eabd71
  labels:
    app.kubernetes.io/name: scheduler-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: scheduler-api
  namespace: scheduler
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: scheduler-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP