apiVersion: apps/v1
kind: Deployment
metadata:
  name: noticegen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: noticegen
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/modeseven/scheduler.git
      labels:
        app.kubernetes.io/name: noticegen
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: noticegen-config
        image: modeseven/noticegen
        imagePullPolicy: Always
        name: noticegen
        volumeMounts:                                               
        - name: quarkus-config-volume                               
          mountPath: /deployments/config 
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumes:                                                      
      - name: quarkus-config-volume                               
        configMap:                                                
          name: noticegen-config
