# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: staging
commonAnnotations:
  note: scheduler-nt staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../services/nats
- ../../services/noticegen
- ../../services/postgres
- ../../services/scheduler-api
- ../../services/scheduler-ui
namespace: scheduler-staging
images:
- name: modeseven/noticegen
  newTag: master-73b26583
- name: modeseven/scheduler-api
  newTag: develop-706ac6ab
- name: modeseven/scheduler-ui
  newTag: develop-3c37b350
patchesStrategicMerge:
- env-cm-patch.yml
