# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: staging
commonAnnotations:
  note: scheduler-nt staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../services/nats
- ../../services/noticegen
- ../../services/scheduler-api
- ../../services/scheduler-ui
- ../../services/postgres
- ../../services/elastic
namespace: scheduler-staging
images:
- name: modeseven/noticegen
  newTag: master-b9311578
- name: modeseven/scheduler-api
  newTag: master-b6d6aceb
- name: modeseven/scheduler-ui
  newTag: master-c74e80d5
patchesStrategicMerge:
- env-cm-patch.yml
- increase-replicas.yml
- ingress.yml
