# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: staging
commonAnnotations:
  note: scheduler-nt staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#- ../../base
resources:
- ../../base
- ../../services/nats
- ../../services/noticegen
- ../../services/postgres
- ../../services/scheduler-api
- ../../services/scheduler-ui
namespace: scheduler-staging
images:
- name: modeseven/noticegen
  newTag: master-214b0e49
- name: modeseven/scheduler-api
  newTag: develop-d8b80025
- name: modeseven/scheduler-ui
  newTag: master-d40cdc80
