# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: staging
commonAnnotations:
  note: scheduler-nt staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#- ../../base
resources:
- ../../base
- ../../services/nats
- ../../services/noticegen
- ../../services/postgres
- ../../services/scheduler-api
- ../../services/scheduler-ui
namespace: scheduler-staging
images:
- name: modeseven/noticegen
  newTag: develop-a4860107
- name: modeseven/scheduler-api
  newTag: develop-91c863c0
- name: modeseven/scheduler-ui
  newTag: develop-911d81da
patchesStrategicMerge:
- api-configmap.yml
