apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-api
  annotations:
    flux.weave.works/automated: "true"
spec:
  template:
    spec:
      $setElementOrder/containers:
        - name: scheduler-api
      containers:
        - image: docker.io/modeseven/scheduler-api:938c1e3888f4a96835e67a1ab1e7e9782989f975
          name: scheduler-api
