---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  name: scheduler-api
  namespace: develop
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: scheduler-api
      containers:
      - image: docker.io/modeseven/scheduler-api:b8b37be6a1b14bc32e8ef144a7df2baba9f3166d
        name: scheduler-api
