apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: scheduler
  annotations:
    app.quarkus.io/vcs-url: https://github.com/modeseven/scheduler-ui.git
  name: scheduler-ui
  labels:
    app: scheduler-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-ui
  template:
    metadata:
      labels:
        app: scheduler-ui
    spec:
      containers:
        - name: scheduler-ui
          image: docker.io/modeseven/scheduler-ui
          ports:
            - containerPort: 80