apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgrespw
  namespace: postgres-ha
spec:
  encryptedData:
    postgrespw: AgBsRpB1+5IFrzzaW6yQ3+2222KtEW34q31TmD3/peZeUqNmByskVs+V/o0OcUULqq6FvOyyqElVe9eOvye0YeH59oV46Thmk+skCRj0myjLNneS6EFFQ2fvKGhHRwW9xGJl+sP5gmyS/vs85cl5c9ymj8sphXdJTlhARKkMrie8Hy+zBGdWZdl13QxljOfvPk3h/vywsR3R5abVGRyjVz54SoFeuVe2mecBTi/S2MeO3f/HYaiAitonvS4xTnkGa529DTIcxEiC7MOdIhGvfP9JkA2JENiyHfq36G7gspej5cIvXbpY0X8ZVuCtICHuM59JFjerFhGHTodkkkl0ZN5Qyz6njQ6TVZL7Lv7eXBLYSS4VkfNm2bgyTGsPNxFubqXPr/cnEWN2Py+vsMUN8a37vieOMVEdHTi8f7Xj6+Txe0shi1uvZ9EOVnwokV+pBlQ4LwwlNUnUa9N6+rOhCfIDbxoI+2RTm7lEAb8jS32hvZiwQJ9KkShW9WD3DtX/x1DDKwm2HhZMpXV5aN5IfyN22SV3qTQO/VnF7vSJxGHkeYg7UOipdKTW9VTOTCWECQW3XDyYhXiJdohJoRx5Do2A0aZQlyztwcOLuhueoJ7APdbFWOatliZrEGBSkldSjW7V5khHpU7hVBNneF77evrnDakmF8t5UX+fbx3uQrK/sfYFBaaiiDLyXEqfOkhakXlhqQOax4/AS+tO
  template:
    metadata:
      creationTimestamp: null
      name: postgrespw
      namespace: scheduler
