apiVersion: v1
kind: ConfigMap
metadata:
  namespace: scheduler
  name: scheduler-config
  labels:
    app: scheduler
data:
  POSTGRES_DB: scheduler
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres-headless
  TEST_PROP: testing1238
  application.properties: |-
    nats.host=nats
    nats.port=4223

