apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        envFrom:
        - secretRef:
            name: postgrespw
        - configMapRef:
            name: scheduler-config
        image: modeseven/scheduler-api
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
        name: scheduler-api
        volumeMounts:                                               
        - name: quarkus-config-volume                               
          mountPath: /deployments/config 
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      volumes:                                                      
      - name: quarkus-config-volume                               
        configMap:                                                
          name: scheduler-config
