apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgrespw
  namespace: develop
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCZsZA+EGfQ2dVYJM18gQuGsBKWzxo4uZMy/yHm7aNiFxAY0/dp7cuS2zo0A6/iT3Rq8mzsvTKYgI5bQxXR2w4ay7eUi8QTCWrfuSKq1islAMKtQDTND52PTz5ms4pAaijd7zTZdfwdG7b4x7NHQip2tXWJIwxYBdBP7AfpIuR39WKq6kZ4a2T/KAvofuFo0G6Wwk0PMJam2xTrPau+ichm1vsh9Wdbwd4Ov6ICwhI1uPvP+A1Ieaf4ATbIboGyVLK4F2SNxgJeXVQeBLJZPtl5vU8R1ItBLhG0MVKGG6oIg2ZsdtGW1FlibqUNxlOtqzwAO05UncdS/oSnGsg7NFfM5REvkSen9iJa/5VMt3DiRojkFD9QLmHlyIwK5W89rQ7NobPzJM22cF/7x+yGbigbdZFQ6yEk8uM686kC4BPJk+DB+hEtzOWcpZvcKITAmAA92WJYdhR9WwooEE9ptb0j7101psa9jZV5bfKrg7Cq/euC5OK85a9pwkVM89Dq76diwEncjJghahxauL9K2q6pAHA4kMc6BufxsOEjmKF3WYev521ssxM7NnpYLfHLWMozbNkE8ks460XMmABBEpG4nZal6aKkD4lNd3I8i+leaYXn9LmC2SuZ7Ewsi6XGg6E/I4GzdpIKT1kvwnk6NNk8P4tcBbYM75RbvOAJg/e8ofOCY/+zcdaS9Y/qTJkA3nzI34TMCZyaplWe
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgrespw
      namespace: develop

