apiVersion: v1
kind: Service
metadata:
  name: scheduler-api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: scheduler-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP