apiVersion: v1
kind: Service
metadata:
  name: elastic
  labels:
    app: elastic
spec:
  selector:
    app: elastic
  type: ClusterIP
  ports:
    - port: 9200
      name: elastic-a
    - port: 9300
      name: elastic-b