apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scheduler-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 1M
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - scheduler.michaelbegley.com
    secretName: scheduler-michaelbegley-com-tls
  rules:
  - host: scheduler.michaelbegley.com
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: scheduler-ui
          servicePort: 80
      - path: /api?(.*)
        backend:
          serviceName: scheduler-api
          servicePort: 8080
      - path: /ng?(.*)
        backend:
          serviceName: noticegen
          servicePort: 8080