apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scheduler-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "1M"
spec:
  tls:
  - hosts:
    - scheduler.mbegley.net
    secretName: scheduler-mbegley-net-tls
  rules:
  - host: scheduler.mbegley.net
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: scheduler-ui
          servicePort: 80
      - path: /api?(.*)
        backend:
          serviceName: scheduler-api
          servicePort: 8080
      - path: /ng?(.*)
        backend:
          serviceName: noticegen
          servicePort: 8080