# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: prod
commonAnnotations:
  note: scheduler-nt prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../services/nats
- ../../services/noticegen
- ../../services/scheduler-api
- ../../services/scheduler-ui
namespace: scheduler-prod
images:
- name: modeseven/noticegen
  newTag: develop-a4860107
- name: modeseven/scheduler-api
  newName: modeseven/scheduler-api-prod
- name: modeseven/scheduler-api-prod
  newTag: prod-8384afcb
- name: modeseven/scheduler-ui
  newTag: master-37398fb5
patchesStrategicMerge:
- increase-replicas.yml
- ingress.yml
- env-cm-patch.yml
