# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: prod
commonAnnotations:
  note: scheduler-nt prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../services/nats
- ../../services/noticegen
- ../../services/postgres
- ../../services/scheduler-api
- ../../services/scheduler-ui
namespace: scheduler-prod
images:
- name: modeseven/noticegen
  newTag: master-a4860107
- name: modeseven/scheduler-api
  newTag: master-60f3d872
- name: modeseven/scheduler-ui
  newTag: master-d40cdc80
patchesStrategicMerge:
- increase-replicas.yml
- api-configmap.yml
