# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: prod
commonAnnotations:
  note: scheduler-nt prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../services/nats
- ../../services/noticegen
- # ../../services/postgres
- ../../services/scheduler-api
- ../../services/scheduler-ui
namespace: scheduler-prod
images:
- name: modeseven/noticegen
  newTag: master-73b26583
- name: modeseven/scheduler-api
  newTag: develop-fc482ffa
- name: modeseven/scheduler-ui
  newTag: develop-2160f64f
patchesStrategicMerge:
- increase-replicas.yml
- ingress.yml
- env-cm-patch.yml
