# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: prod
commonAnnotations:
  note: scheduler-nt prod
# - ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../services/nats
- ../../services/noticegen
- ../../services/postgres
- ../../services/scheduler-api
- ../../services/scheduler-ui
namespace: scheduler-prod
images:
- name: modeseven/noticegen
  newTag: master-214b0e49
- name: modeseven/scheduler-api
  newTag: develop-048b34b7
- name: modeseven/scheduler-ui
  newTag: master-788885b9
patchesStrategicMerge:
- increase-replicas.yml
