# namePrefix: dev-
commonLabels:
  org: mbegley
  variant: prod
commonAnnotations:
  note: scheduler-nt prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../services/nats
- ../../services/noticegen
- ../../services/scheduler-api
- ../../services/scheduler-ui
- ../../services/postgres
images:
- name: modeseven/noticegen
  newTag: v0.0.1-beta
- name: modeseven/scheduler-api
  newTag: v.0.0.7
- name: modeseven/scheduler-ui
  newTag: v0.0.1-beta
patchesStrategicMerge:
- increase-replicas.yml
- ingress.yml
- env-cm-patch.yml
